@ECHO OFF
echo Creating Control flow graph...
cfg.exe
echo Appending new edges in control flow graph...
php -f newNodes.php
echo Path generation from control flow graph...
cfg_path.exe
echo Generating executable test path using DU information...
finalPath.exe
echo successfull...
resultCalc.exe
start files\Result.txt
@ECHO OFF
pause