test.c
SUBSYS
SUBSYS
struct workqueue_struct* cgroup_destroy_wq
struct workqueue_struct* cgroup_pidlist_destroy_wq
struct cgroup_root cgrp_dfl_root
Referenced by cgroup_destroy_root, cgroup_mount, rebind_subsystems, cgroup_remount, cgroup_setup_root, cgroup_kill_sb.
bool cgrp_dfl_root_visible
Referenced by cgroup_mount, rebind_subsystems.
bool cgroup_legacy_files_on_dfl
unsigned int cgrp_dfl_root_inhibit_ss_mask
Referenced by rebind_subsystems.
int cgroup_root_count
Referenced by find_css_set, cgroup_destroy_root, cgroup_setup_root.
u64 css_serial_nr_next
int need_forkexit_callback __read_mostly
struct cftype cgroup_dfl_base_files[][]
Referenced by cgroup_setup_root.
struct cftype cgroup_legacy_base_files[][]
Referenced by cgroup_setup_root.
DEFINE_SPINLOCK(cgroup_idr_lock)
DEFINE_SPINLOCK(release_agent_path_lock)
LIST_HEAD(cgroup_roots)
Referenced by cgroup_setup_root.
DEFINE_IDR(cgroup_hierarchy_idr)
int rebind_subsystems(struct cgroup_root *dst_root, unsigned int ss_mask)
References cgroup_css, cgrp_dfl_root, cgrp_dfl_root_inhibit_ss_mask, cgroup_populate_dir, cgrp_dfl_root_visible, cgroup_clear_dir, cgroup_refresh_child_subsys_mask.
Referenced by cgroup_destroy_root, cgroup_remount, cgroup_setup_root.
int cgroup_destroy_locked(struct cgroup *cgrp)
int create_css(struct cgroup *cgrp, struct cgroup_subsys *ss, bool visible)
void css_release(struct percpu_ref *ref)
void kill_css(struct cgroup_subsys_state *css)
int cgroup_addrm_files(struct cgroup *cgrp, struct cftype cfts[], bool is_add)
Referenced by cgroup_populate_dir, cgroup_clear_dir, cgroup_setup_root.
int cgroup_idr_alloc(struct idr *idr, void *ptr, int start, int end, gfp_t gfp_mask)
Referenced by cgroup_setup_root.
void* cgroup_idr_replace(struct idr *idr, void *ptr, int id)
void cgroup_idr_remove(struct idr *idr, int id)
struct cgroup* cgroup_parent(struct cgroup *cgrp)
Referenced by cgroup_e_css, cgroup_get_e_css, cgroup_is_descendant, cgroup_update_populated, cgroup_calc_child_subsys_mask.
struct cgroup_subsys_state* cgroup_css(struct cgroup *cgrp, struct cgroup_subsys *ss)
Referenced by cgroup_e_css, cgroup_get_e_css, rebind_subsystems.
struct cgroup_subsys_state* cgroup_e_css(struct cgroup *cgrp, struct cgroup_subsys *ss)
References cgroup_parent, cgroup_css.
Referenced by find_existing_css_set.
struct cgroup_subsys_state* cgroup_get_e_css(struct cgroup *cgrp, struct cgroup_subsys *ss)
References cgroup_css, cgroup_parent.
bool cgroup_is_dead(const struct cgroup *cgrp)
Referenced by cgroup_get, cgroup_kn_lock_live.
struct cgroup_subsys_state* of_css(struct kernfs_open_file *of)
bool cgroup_is_descendant(struct cgroup *cgrp, struct cgroup *ancestor)
References cgroup_parent.
int notify_on_release(const struct cgroup *cgrp)
void cgroup_update_populated(struct cgroup *cgrp, bool populated)
References cgroup_parent.
Referenced by put_css_set_locked, link_css_set.
unsigned long css_set_hash(struct cgroup_subsys_state *css[])
Referenced by find_existing_css_set, find_css_set.
void put_css_set_locked(struct css_set *cset)
References cgroup_update_populated.
Referenced by put_css_set.
void put_css_set(struct css_set *cset)
References put_css_set_locked.
void get_css_set(struct css_set *cset)
Referenced by find_css_set, cgroup_enable_task_cg_lists.
bool compare_css_sets(struct css_set *cset, struct css_set *old_cset, struct cgroup *new_cgrp, struct cgroup_subsys_state *template[])
Referenced by find_existing_css_set.
struct css_set* find_existing_css_set(struct css_set *old_cset, struct cgroup *cgrp, struct cgroup_subsys_state *template[])
References cgroup_e_css, css_set_hash, compare_css_sets.
Referenced by find_css_set.
void free_cgrp_cset_links(struct list_head *links_to_free)
Referenced by allocate_cgrp_cset_links, cgroup_setup_root.
int allocate_cgrp_cset_links(int count, struct list_head *tmp_links)
References free_cgrp_cset_links.
Referenced by find_css_set.
void link_css_set(struct list_head *tmp_links, struct css_set *cset, struct cgroup *cgrp)
References cgroup_update_populated.
Referenced by find_css_set, cgroup_setup_root.
struct css_set* find_css_set(struct css_set *old_cset, struct cgroup *cgrp)
References find_existing_css_set, get_css_set, allocate_cgrp_cset_links, cgroup_root_count, link_css_set, css_set_hash.
struct cgroup_root* cgroup_root_from_kf(struct kernfs_root *kf_root)
Referenced by cgroup_show_options, cgroup_remount, cgroup_kill_sb.
int cgroup_init_root_id(struct cgroup_root *root)
void cgroup_exit_root_id(struct cgroup_root *root)
Referenced by cgroup_destroy_root, cgroup_setup_root.
int cgroup_populate_dir(struct cgroup *cgrp, unsigned int subsys_mask)
References cgroup_addrm_files, cgroup_clear_dir.
Referenced by rebind_subsystems.
void cgroup_free_root(struct cgroup_root *root)
Referenced by cgroup_destroy_root, cgroup_mount.
void cgroup_destroy_root(struct cgroup_root *root)
References rebind_subsystems, cgrp_dfl_root, cgroup_root_count, cgroup_exit_root_id, cgroup_free_root.
struct cgroup* cset_cgroup_from_root(struct css_set *cset, struct cgroup_root *root)
Referenced by task_cgroup_from_root.
struct cgroup* task_cgroup_from_root(struct task_struct *task, struct cgroup_root *root)
References cset_cgroup_from_root.
char* cgroup_file_name(struct cgroup *cgrp, const struct cftype *cft, char *buf)
Referenced by cgroup_rm_file.
struct dentry* cgroup_mount(struct file_system_type *fs_type, int flags, const char *unused_dev_name, void *data)
References parse_cgroupfs_options, cgrp_dfl_root_visible, cgrp_dfl_root, cgroup_get, cgroup_put, init_cgroup_root, cgroup_setup_root, cgroup_free_root.
umode_t cgroup_file_mode(const struct cftype *cft)
void cgroup_get(struct cgroup *cgrp)
References cgroup_is_dead.
Referenced by cgroup_mount.
bool cgroup_tryget(struct cgroup *cgrp)
Referenced by cgroup_kn_lock_live.
void cgroup_put(struct cgroup *cgrp)
Referenced by cgroup_mount, cgroup_kn_unlock, cgroup_kill_sb.
unsigned int cgroup_calc_child_subsys_mask(struct cgroup *cgrp, unsigned int subtree_control)
References cgroup_parent.
Referenced by cgroup_refresh_child_subsys_mask.
void cgroup_refresh_child_subsys_mask(struct cgroup *cgrp)
References cgroup_calc_child_subsys_mask.
Referenced by rebind_subsystems.
void cgroup_kn_unlock(struct kernfs_node *kn)
References cgroup_put.
Referenced by cgroup_kn_lock_live.
struct cgroup* cgroup_kn_lock_live(struct kernfs_node *kn)
References cgroup_tryget, cgroup_is_dead, cgroup_kn_unlock.
void init_cgroup_root(struct cgroup_root *root, struct cgroup_sb_opts *opts)
References init_cgroup_housekeeping.
Referenced by cgroup_mount.
void cgroup_rm_file(struct cgroup *cgrp, const struct cftype *cft)
References cgroup_file_name.
void cgroup_clear_dir(struct cgroup *cgrp, unsigned int subsys_mask)
References cgroup_addrm_files.
Referenced by cgroup_populate_dir, rebind_subsystems.
int cgroup_show_options(struct seq_file *seq, struct kernfs_root *kf_root)
References cgroup_root_from_kf.
int parse_cgroupfs_options(char *data, struct cgroup_sb_opts *opts)
Referenced by cgroup_mount, cgroup_remount.
int cgroup_remount(struct kernfs_root *kf_root, int *flags, char *data)
References cgroup_root_from_kf, cgrp_dfl_root, parse_cgroupfs_options, rebind_subsystems.
void cgroup_enable_task_cg_lists(void)
References get_css_set.
void init_cgroup_housekeeping(struct cgroup *cgrp)
Referenced by init_cgroup_root.
int cgroup_setup_root(struct cgroup_root *root, unsigned int ss_mask)
References LIST_HEAD, cgroup_idr_alloc, cgrp_dfl_root, cgroup_dfl_base_files, cgroup_legacy_base_files, cgroup_addrm_files, rebind_subsystems, cgroup_root_count, link_css_set, cgroup_exit_root_id, free_cgrp_cset_links.
Referenced by cgroup_mount.
void cgroup_kill_sb(struct super_block *sb)
References cgroup_root_from_kf, cgrp_dfl_root, cgroup_put.